[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "python3.11 -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip setuptools wheel",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]

[start]
cmd = "/opt/venv/bin/python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
